### ISSUE TITLE
能否将disconf的配置信息移动到 bootstrap.properties 中?

### ISSUE THREAD

**Issue by xiangzhurui** [xjzrc/disconf-spring-boot-starter#2]
嗨，首先感谢作者提供的starter。
如题所示，能否支持将 conf-server-host 这些disconf的配置移动到  bootstrap.properties （就像spring-config的模式）以便于配置中心托管 application.properties 或其他动态配置。

目前我的临时方案实现是将 disconf starter 的源码移动到主项目中并给`DisconfProperties`类增加了`@Configuration` 和 `@PropertySource` ，如下所示。但如此一来实际上就没有使用自动配置的starter了
```java
@Configuration
@PropertySource(value = "classpath:bootstrap.properties")
@ConfigurationProperties(DisconfProperties.DISCONF_PROPERTIES_PREFIX)
public class DisconfProperties
```

**Comment by xjzrc** [comment]
@xiangzhurui 首先，感谢的你关注。

disconf不就是项目的配置中心吗？项目引入了disconf，应该一切配置都交给disconf来管理，除了disconf本身的配置。

你想将conf-server-host单独出来配置，是不是有多套disconf环境？不同的包用不同的disconf环境？  如果是这样，有两种方案解决：

1.springboot本身支持多环境配置。

2.如果是maven项目，可以将conf-server-host等配置信息配置在pom文件中。

这样通过不同的打包命令就可以动态生成disconf的配置信息。

**Comment by xiangzhurui** [comment]
@xjzrc 感谢回复。

的确是多套 disconf 环境。但不是不同的包不同的 disconf 环境，而是相同的包使用不同的 disconf 环境

目前要求线上和测试环境使用的包完全一致，所以在不能再打包阶段传入disconf环境信息，生成不同的部署包。
springboot本身支持多环境配置 是不是指 spring.profiles.active 选项？就我目前了解到的是这个方式在编译打包阶段就需要确定多disconf环境的配置。两套disconf 环境 是分别有两组人管理的（研发是不能直接操作线上和预发的disconf）

而想将 配置中心相关的配置 分离出来，一方面觉得配置中心客户端应该在主体应用启动之前启动并拉取配置，另一方面是感觉这个配置中心的配置和应用配置混合在一起的方式不太优雅。

> 最近一些时间是有将工作项目换为 Spring boot 的想法，也是想找一个 starter或自己写一个出来。但disconf 的源码看来看去总感觉与 Spring boot 本身的风格不太一致，需要修改一番，而个人去升级重构目前看来又有些任重道远。。。

**Comment by xjzrc** [comment]
@xiangzhurui 下面是我们使用的情况，你可以参考下：
> 我们的项目有3种运行环境，分别是开发、测试和生产。
> 其中开发和测试共用一套disconf环境如：disconf-sit.github.com
> 生产使用的disconf环境是：disconf.github.com
具体的配置如下：

pom文件中的环境参数配置
```xml
<profiles>
        <profile>
            <id>dev</id>
            <properties>
                <spring.profiles>dev</spring.profiles>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>uat</id>
            <properties>
                <spring.profiles>uat</spring.profiles>
            </properties>
        </profile>
        <profile>
            <id>prd</id>
            <properties>
                <spring.profiles>online</spring.profiles>
            </properties>
        </profile>
</profiles>
```
spring-boot默认文件配置application.yml
```yml
spring:
  profiles:
    active: @spring.profiles@
  aop:
    #使你的项目支持 cglib的aop
    proxy-target-class: true
  disconf:
    #disconf包扫描路径
    scan-package: com.zen.spring.boot.demo.disconf
    #不需要自动reload的配置文件
    un-reload-files: myserver.properties
    #需要自动reload的配置文件
    reload-files: autoconfig.properties,autoconfig2.properties,myserver_slave.properties,testJson.json,testXml2.xml
    #是否使用远程配置文件，true(默认)会从远程获取配置 false则直接获取本地配置
    enable-remote-conf: true
    #配置服务器的 HOST(必填)，用逗号分隔  127.0.0.1:8000,127.0.0.1:8000
    #conf-server-host: 127.0.0.1
    #APP 请采用 产品线_服务名 格式
    app: disconf-demo
    #环境
    #env: rd
    #版本, 请采用 X_X_X_X 格式,注意要用单引号，不然Springboot将会解析成1000
    version: '1_0_0_0'
    #忽略哪些分布式配置，用逗号分隔
    ignore:
    #调试模式。调试模式下，ZK超时或断开连接后不会重新连接（常用于client单步debug）。非调试模式下，ZK超时或断开连接会自动重新连接。
    debug: false
    #获取远程配置 重试次数，默认是3次
    conf-server-url-retry-times: 1
    #获取远程配置 重试时休眠时间，默认是5秒
    conf-server-url-retry-sleep-seconds: 1
    #用户定义的下载文件夹, 远程文件下载后会放在这里。注意，此文件夹必须有有权限，否则无法下载到这里
    user-define-download-dir: /app/spring-boot/disconf/disconf-spring-boot-starter-demo
    #下载的文件会被迁移到classpath根路径下(默认是false)
    enable-local-download-dir-in-class-path: false
```
application-dev.yml配置
```yml
spring:
  disconf:
    #配置服务器的 HOST(必填)，用逗号分隔  127.0.0.1:8000,127.0.0.1:8000
    conf-server-host: disconf-sit.github.com
    #环境    
    env: rd
```
application-uat.yml配置
```yml
spring:
  disconf:
    #配置服务器的 HOST(必填)，用逗号分隔  127.0.0.1:8000,127.0.0.1:8000
    conf-server-host: disconf-sit.github.com
    #环境    
    env: qa
```
application-online.yml配置
```yml
spring:
  disconf:
    #配置服务器的 HOST(必填)，用逗号分隔  127.0.0.1:8000,127.0.0.1:8000
    conf-server-host: disconf.github.com
    #环境    
    env: online
```
不同环境打包命令：
> 默认开发环境：
```script
mvn clean package -Dmaven.test.skip=true -P dev -U
```
> 测试环境：
```script
mvn clean package -Dmaven.test.skip=true -P uat -U
```
>生产环境：
```script
mvn clean package -Dmaven.test.skip=true -P prd -U
```
